from enum import StrEnum
from typing import Any, Generic, TypeVar

from pydantic import BaseModel


DataT = TypeVar("DataT")


class ErrorCode(StrEnum):
    # frontend 메시지 매핑 기준이 되는 안정적인 오류 코드
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_LOGOUT_FAILED = "AUTH_LOGOUT_FAILED"
    GOAL_NOT_FOUND = "GOAL_NOT_FOUND"
    GOAL_CREATE_FAILED = "GOAL_CREATE_FAILED"
    GOAL_UPDATE_FAILED = "GOAL_UPDATE_FAILED"
    GOAL_DELETE_FAILED = "GOAL_DELETE_FAILED"
    GOAL_INVALID_DEADLINE = "GOAL_INVALID_DEADLINE"
    MILESTONE_NOT_FOUND = "MILESTONE_NOT_FOUND"
    MILESTONE_CREATE_FAILED = "MILESTONE_CREATE_FAILED"
    MILESTONE_UPDATE_FAILED = "MILESTONE_UPDATE_FAILED"
    MILESTONE_DELETE_FAILED = "MILESTONE_DELETE_FAILED"
    MILESTONE_INVALID_SCHEDULED_DATE = "MILESTONE_INVALID_SCHEDULED_DATE"
    CALENDAR_INVALID_MONTH = "CALENDAR_INVALID_MONTH"
    CALENDAR_INVALID_DATE = "CALENDAR_INVALID_DATE"
    CALENDAR_QUERY_FAILED = "CALENDAR_QUERY_FAILED"
    SETTINGS_NOT_FOUND = "SETTINGS_NOT_FOUND"
    SETTINGS_UPDATE_FAILED = "SETTINGS_UPDATE_FAILED"
    SETTINGS_INVALID_VALUE = "SETTINGS_INVALID_VALUE"
    SUPABASE_UNAVAILABLE = "SUPABASE_UNAVAILABLE"
    SUPABASE_REQUEST_FAILED = "SUPABASE_REQUEST_FAILED"
    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"


class SuccessResponse(BaseModel, Generic[DataT]):
    # 성공 응답 envelope: data 타입만 endpoint별로 변경
    success: bool = True
    data: DataT


class ErrorBody(BaseModel):
    # 사용자 표시 메시지와 디버깅 detail 분리
    code: ErrorCode | str
    message: str
    detail: Any | None = None


class ErrorResponse(BaseModel):
    # 실패 응답 envelope: request_id로 로그 추적
    success: bool = False
    error: ErrorBody
    request_id: str
